# Selecionar todos os projetos
SELECT *
FROM PROJETOS;

#Selecionar um usuário específico pelo ID
SELECT ID, NOME, EMAIL, CPF, TELEFONE, CEP, TIPO
FROM USUARIO
WHERE ID = 1;

# Selecionando todos os projetos de um usuário específico
SELECT P.COD, P.NOME, P.DESCRICAO, P.VALOR_TOTAL, P.IMAGEM
FROM PROJETOS P
INNER JOIN USUARIO_PROJETO UP ON P.COD = UP.FK_PROJETOS_COD
WHERE UP.FK_USUARIO_ID = 1; 

# Selecionar todas as mensagens trocadas entre dois usuários
SELECT C.ID, C.REMETENTE_ID, C.DESTINATARIO_ID, C.MENSAGEM, C.DATA_HORA, U1.NOME AS REMETENTE, U2.NOME AS DESTINATARIO
FROM CHAT C
INNER JOIN USUARIO U1 ON C.REMETENTE_ID = U1.ID
INNER JOIN USUARIO U2 ON C.DESTINATARIO_ID = U2.ID
WHERE (C.REMETENTE_ID = 1 AND C.DESTINATARIO_ID = 2) 
   OR (C.REMETENTE_ID = 2 AND C.DESTINATARIO_ID = 1)
   ORDER BY c.DATA_HORA ASC;
   
# Selecionar o perfil de um usuário específico
SELECT PU.ID, PU.FK_USUARIO_ID, PU.BIOGRAFIA, U.NOME, U.EMAIL, U.TELEFONE, U.CPF, U.CEP
FROM PERFIL_USUARIO PU
INNER JOIN USUARIO U ON PU.FK_USUARIO_ID = U.ID
WHERE PU.FK_USUARIO_ID = 1; 

# Selecionar todos os pagamentos feitos por um usuário para um projeto específico
SELECT P.ID, P.FK_USUARIO_ID, P.FK_PROJETOS_COD, P.FK_FORMA_PAGAMENTO_ID, P.VALOR_PAGO, P.DATA_PAGAMENTO, FP.NOME AS FORMA_PAGAMENTO
FROM PAGAMENTOS P
INNER JOIN FORMAS_PAGAMENTO FP ON P.FK_FORMA_PAGAMENTO_ID = FP.ID
WHERE P.FK_USUARIO_ID = 1 AND P.FK_PROJETOS_COD = 1;

#listar o total de pagamentos recebidos por projeto
SELECT PR.NOME AS PROJETO, SUM(P.VALOR_PAGO) AS TOTAL_ARRECADADO
FROM PAGAMENTOS P
INNER JOIN PROJETOS PR ON P.FK_PROJETOS_COD = PR.COD
GROUP BY PR.NOME;

   