#TELA INICIAL
# Selecionar todos os projetos
SELECT NOME,DESCRICAO, IMAGEM, VALOR_TOTAL
FROM PROJETOS;

#TELA DE PERFIL
#Selecionar um usuário específico pelo ID
SELECT NOME, EMAIL, CPF, TELEFONE, CEP,FOTO, BIOGRAFIA
FROM USUARIO
WHERE ID = 1;

#TELA ACOMPANHAMENTO DE INVESTIMENTO
# Selecionando todos os projetos de um usuário específico
SELECT  P.NOME, P.DESCRICAO, P.VALOR_TOTAL, P.IMAGEM
FROM PROJETOS P
INNER JOIN USUARIO_PROJETO UP ON P.COD = UP.FK_PROJETOS_COD
WHERE UP.FK_USUARIO_ID = 1; 

#listar o total de pagamentos recebidos por projeto
SELECT PR.NOME AS PROJETO, SUM(P.VALOR_PAGO) AS TOTAL_ARRECADADO
FROM PAGAMENTOS P
INNER JOIN PROJETOS PR ON P.FK_PROJETOS_COD = PR.COD
GROUP BY PR.NOME;

#TELA DE CONVERSA
# Selecionar todas as mensagens trocadas entre dois usuários
SELECT  C.REMETENTE_ID, C.DESTINATARIO_ID, C.MENSAGEM, C.DATA_HORA, U1.NOME AS REMETENTE, U2.NOME AS DESTINATARIO
FROM CHAT C
INNER JOIN USUARIO U1 ON C.REMETENTE_ID = U1.ID
INNER JOIN USUARIO U2 ON C.DESTINATARIO_ID = U2.ID
WHERE (C.REMETENTE_ID = 1 AND C.DESTINATARIO_ID = 2) 
   OR (C.REMETENTE_ID = 2 AND C.DESTINATARIO_ID = 1)
   ORDER BY c.DATA_HORA ASC;

#TELA DOS CONTATOS
SELECT U.NOME,U.FOTO 
FROM CONTATOS C
JOIN USUARIO U ON C.FK_USUARIO_ID2 = U.ID
WHERE C.FK_USUARIO_ID1 = 1;

#TELA PROJETO COMPLETO/ PROJETO DETALHADO
SELECT IMAGEM, NOME, DESCRICAO, VALOR_TOTAL
FROM PROJETOS
WHERE ID = 1;

#TELA DE PAGAMENTO
SELECT IMAGEM, NOME
FROM PROJETOS
WHERE ID = 1;

#TELA DE FORMA DE PAGAMENTO
SELECT P.IMAGEM, P.NOME, F.NOME
FROM PROJETOS P
INNER JOIN PAGAMENTOS PA ON P.COD = PA.FK_PROJETOS_COD
INNER JOIN FORMAS_PAGAMENTO F ON F.ID = PA.FK_FORMA_PAGAMENTO_ID;

#TELA CARTÃO
SELECT NOME_TITULAR, NUMERO_CARTAO, VALIDADE, CVV
FROM DADOS_CARTAO
WHERE ID = 1;	