CREATE DATABASE INVESTMENT_BRIDGE;

USE INVESTMENT_BRIDGE;

CREATE TABLE INVESTIDOR(
	
	ID INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(20) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(19) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE CLIENTE(

	ID INT PRIMARY KEY AUTO_INCREMENT,
	TIPO VARCHAR(25) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    TELEFONE VARCHAR(19) UNIQUE,
    EMAIL VARCHAR(100) UNIQUE,
    ENDERECO VARCHAR(70),
    UF VARCHAR(2)
);

CREATE TABLE PROJETOS(

	COD INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
    TIPO VARCHAR(25) NOT NULL,
    NECESSIDADE_INVESTIMENTO VARCHAR(200) NOT NULL, 
    VALOR_TOTAL DOUBLE
); 

CREATE TABLE INVESTIDOR_CLIENTE(

	FK_INVESTIDOR_ID INT,
    FK_CLIENTE_ID INT,
    FOREIGN KEY(FK_INVESTIDOR_ID) REFERENCES INVESTIDOR(ID),
    FOREIGN KEY(FK_CLIENTE_ID) REFERENCES CLIENTE(ID),
    PRIMARY KEY(FK_INVESTIDOR_ID, FK_CLIENTE_ID)
);

CREATE TABLE INVESTIDOR_PROJETO(

	FK_INVESTIDOR_ID INT,
    FK_PROJETOS_COD INT,
    VALOR_NEGOCIADO DOUBLE,
    DATA DATE,
    FOREIGN KEY(FK_INVESTIDOR_ID) REFERENCES INVESTIDOR(ID),
    FOREIGN KEY(FK_PROJETOS_COD) REFERENCES PROJETOS(COD),
    PRIMARY KEY(FK_INVESTIDOR_ID, FK_PROJETOS_COD)
);

CREATE TABLE CLIENTE_PROJETO(

	FK_CLIENTE_ID INT,
    FK_PROJETOS_COD INT,
    FOREIGN KEY(FK_CLIENTE_ID) REFERENCES CLIENTE(ID),
    FOREIGN KEY(FK_PROJETOS_COD) REFERENCES PROJETOS(COD),
    PRIMARY KEY(FK_CLIENTE_ID, FK_PROJETOS_COD)
);

CREATE TABLE CHAT(
	
	ID INT AUTO_INCREMENT PRIMARY KEY,
	FK_INVESTIDOR_ID INT,
    FK_CLIENTE_ID INT,
    ARMAZENAR TEXT,
    FOREIGN KEY(FK_INVESTIDOR_ID) REFERENCES INVESTIDOR(ID),
    FOREIGN KEY(FK_CLIENTE_ID) REFERENCES CLIENTE(ID)
);