CREATE DATABASE INVESTMENT_BRIDGE;
USE INVESTMENT_BRIDGE;

-- Tabela USUARIO
CREATE TABLE USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SENHA VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) UNIQUE,
    CEP VARCHAR(10),
    TELEFONE VARCHAR(19) UNIQUE
);

-- Tabela PROJETOS
CREATE TABLE PROJETOS (
    COD INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    TIPO VARCHAR(25) NOT NULL,
    NECESSIDADE_INVESTIMENTO VARCHAR(200) NOT NULL,
    VALOR_TOTAL DOUBLE
);

-- Tabela USUARIO_PROJETO (associação entre usuário e projeto)
CREATE TABLE USUARIO_PROJETO (
    FK_USUARIO_ID INT,
    FK_PROJETOS_COD INT,
    FOREIGN KEY (FK_USUARIO_ID) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_PROJETOS_COD) REFERENCES PROJETOS(COD),
    PRIMARY KEY (FK_USUARIO_ID, FK_PROJETOS_COD)
);

-- Tabela CHAT (mensagens entre usuários)
CREATE TABLE CHAT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIO_ID INT,
    ARMAZENAR TEXT,
    FOREIGN KEY (FK_USUARIO_ID) REFERENCES USUARIO(ID)
);

-- Tabela PERFIL (informações detalhadas de perfil de usuário)
CREATE TABLE PERFIL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_USUARIO_NOME VARCHAR(50),
    FK_USUARIO_EMAIL VARCHAR(100),
    FK_USUARIO_TELEFONE VARCHAR(19),
    CPF VARCHAR(11),
    CEP VARCHAR(10),
    BIOGRAFIA TEXT,
    FOREIGN KEY (FK_USUARIO_EMAIL) REFERENCES USUARIO(EMAIL),
    FOREIGN KEY (FK_USUARIO_TELEFONE) REFERENCES USUARIO(TELEFONE),
    FOREIGN KEY (FK_USUARIO_NOME) REFERENCES USUARIO(NOME)
);